from financial_statement_analyser.loaders.base import load_statement_by_type
from financial_statement_analyser.loaders.lloyds import load_statement_lloyds
from financial_statement_analyser.loaders.monzo import load_statement_monzo
from financial_statement_analyser.loaders.amex import load_statement_amex
from financial_statement_analyser.loaders.capital_one import load_statement_capital_one
from financial_statement_analyser.loaders.vanguard import load_statement_vanguard
from financial_statement_analyser.loaders.interest import load_statement_interest
from financial_statement_analyser.loaders.pension import load_statement_pension
